app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__,template_folder='templates',static_folder='static')

from . import views

app/main/views.py
from . import main
from uuid import uuid4
from flask import render_template, redirect, flash, url_for, request, make_response, session
from flask import current_app as app
from app.extensions import db, bcrypt
from models import Admin, Config, Content
from sqlalchemy.exc import IntegrityError
from functools import wraps
import datetime as d


@main.route('/', methods=['GET'])
def index():
    return render_template('index.html')


@main.route('/signup/', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        password = bcrypt.generate_password_hash(request.form['password'])
        new_admin = Admin(
            first_name=request.form['firstName'], last_name=request.form['lastName'], email=request.form['email'], password=password, admin_id=str(uuid4()))
        try:
            db.session.add(new_admin)
            db.session.commit()
            flash(u'Welcome, Signup Complete - Login please', 'success')
            return redirect(url_for('main.login')), 200
        except IntegrityError:
            db.session.rollback()
            error = 'User Already Exists'
            return render_template('signup.html', msg=error), 400
    elif request.method == 'GET':
        return render_template('signup.html'), 200


@main.route('/login/', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('login.html')
    elif request.method == 'POST':
        # fetch login details
        email = request.form['email']
        password = request.form['password']
        # find user with matching email
        user = Admin.query.filter_by(email=email).first()
        if not user:
            flash(u"No such user found", 'error')
            return render_template('login.html'), 404
        else:
            if bcrypt.check_password_hash(user.password, password):
                session.permanent = True
                session['admin_id'] = user.admin_id
                return redirect(url_for('main.dashboard')), 200
            flash(u'Incorrect Password', 'error')
            return render_template('login.html'), 400


# Authorization decorator
def login_required(f):
    @wraps(f)
    def function(*args, **kwargs):
        if 'admin_id' in session:
            admin_id = session['admin_id']
            # find admin with matching ID
            user = Admin.query.filter_by(admin_id=admin_id).first()
            if user:
                return f(user, *args, **kwargs)
            else:
                flash(u'Invalid Login credentials', 'error')
                return redirect(url_for('main.login')), 401
        else:
            flash(u'You\'re not logged in', 'error')
            return redirect(url_for('main.login')), 401

    return function


@main.route('/dashboard/', methods=['POST', 'GET'])
@login_required
def dashboard(user):
    if request.method == 'GET':
        return render_template('dashboard.html'), 200
    if request.method == 'POST':
        # content
        logo = request.files.get('site-logo')
        print(logo)
        header_image = request.files.get('header-image')
        about_image = request.files.get('about-image')
        carousel_images = [i.read()
                           for i in request.files.getlist('carousel-images')]
        volunteers = request.form['volunteers'].split(',')
        carousel_info = request.form['carousel-info'].split(',')
        header_info = request.form['header-info'].split(',')
        about_info = request.form['about-info']
        nav_bar = request.form['nav-bar'].split(',')

        # fetch site config
        site_config = Config(
            site_name=request.form['site_name'], logo=logo.read())
        site_content = Content(
            header_image=header_image.read(),
            about_image=about_image.read(),
            carousel_images=carousel_images,
            volunteers=volunteers,
            about_info=about_info,
            nav_bar=nav_bar,
            header_info=header_info,
            carousel_info=carousel_info,
            config=site_config
        )
        db.session.add_all([site_config, site_content])
        try:
            db.session.commit()
            return redirect("https://ohw-ngo.netlify.app/ohw-homepage.html")
        except Exception as e:
            raise e
            return render_template('dashboard.html'), 500

app/main/templates/dashboard.html
<!doctype html>
<html lang="en">

<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, user-scalable=no">
	<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;700&display=swap" rel="stylesheet">
	<link href="http://netdna.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.css" rel="stylesheet">
	<link href="{{url_for('main.static',filename='css/bootstrap.min.css')}}" rel="stylesheet">
	<link href="{{url_for('main.static',filename='css/gsdk-bootstrap-wizard.css')}}" rel="stylesheet">
	<link rel="stylesheet" href="{{url_for('main.static',filename='css/style.css')}}">
	<title>DASHBOARD</title>
</head>

<body class=" site-builder-bg">

	<!--   Big container   -->
	<div class="container">
		<div class="row">
			<div class="col-sm-8 col-sm-offset-2">

				<!--      Wizard container        -->
				<div class="wizard-container">

					<div class="card wizard-card" data-color="orange" id="wizardProfile">
						<form method="POST" enctype='multipart/form-data'>
							<div class="wizard-header donate-text-one">
								<h3>
									<b>SITE </b> BUILDER<br>
									<small>This information will let us know more about you.</small>
								</h3>
							</div>

							<div class="wizard-navigation">
								<ul>
									<li><a href="#about" data-toggle="tab">STEP 1</a></li>
									<li><a href="#account" data-toggle="tab">STEP 2</a></li>
								</ul>
							</div>

							<div class="tab-content">
								<div class="tab-pane" id="about">
									<div class="row">
										<h4 class="info-text">Website Details</h4>
										<div class="col-sm-4 col-sm-offset-1">
											<div class="picture-container">
												<div class="picture">
													<img src="{{url_for('main.static',filename='img/default-avatar.png')}}" class="picture-src" id="wizardPicturePreview" title="" />
													<input type="file" name="site-logo" id="wizard-picture">
												</div>
												<h6>Choose Website Logo</h6>
											</div>
										</div>
										<div class="col-sm-6">
											<div class="form-group">
												<label>Site Name <b class="text-danger">*</b></label>
												<input name="site_name" type="text" class="form-control" placeholder="Ohw">
											</div>
										</div>
									</div>
								</div>
								<div class="tab-pane" id="account">
									<h4 class="info-text">Create your Site</h4>
									<div class="row">
										<div class="col-sm-10 col-sm-offset-1">

											<div class="form-group">
												<label for="exampleFormControlFile1">Header Image <b class="text-danger">*</b></label>
												<input type="file" class="form-control-file" id="exampleFormControlFile1" name="header-image">
											</div>

										</div>
										<div class="col-sm-10 col-sm-offset-1">

											<div class="form-group">
												<label for="exampleFormControlTextarea1">Header Info <b class="text-danger">*</b></label>
												<textarea class="form-control" id="exampleFormControlTextarea1" rows="1" name="header-info"></textarea>
											</div>

										</div>
										<div class="col-sm-10 col-sm-offset-1">

											<div class="form-group">
												<label for="exampleFormControlTextarea1">Navigation Bar <b class="text-danger">*</b></label>
												<textarea class="form-control" id="exampleFormControlTextarea1" rows="1" name="nav-bar"></textarea>
											</div>

										</div>
										<div class="col-sm-10 col-sm-offset-1">
											<div class="form-group">

												<div class="form-group">
													<label for="exampleFormControlFile1">About Image <b class="text-danger">*</b></label>
													<input type="file" class="form-control-file" name="about-image" id="exampleFormControlFile1">
												</div>

											</div>
										</div>
										<div class="col-sm-10 col-sm-offset-1">

											<div class="form-group">
												<label for="exampleFormControlTextarea1">About Info <b class="text-danger">*</b></label>
												<textarea class="form-control" name="about-info" id="exampleFormControlTextarea1" rows="1"></textarea>
											</div>

										</div>
									</div>

									<div class="tab-pane" id="address">
										<div class="row">
											<div class="col-sm-10 col-sm-offset-1">
												<div class="form-group">

													<div class="form-group">
														<label for="exampleFormControlFile1">Carousel Images <b class="text-danger">*</b></label>
														<input type="file" name="carousel-images" class="form-control-file" id="exampleFormControlFile1">
													</div>

												</div>
											</div>
											<div class="col-sm-10 col-sm-offset-1">

												<div class="form-group">
													<label for="exampleFormControlTextarea1">Carousel Info <b class="text-danger">*</b></label>
													<textarea class="form-control" name="carousel-info" id="exampleFormControlTextarea1" rows="1"></textarea>
												</div>

											</div>
											<div class="col-sm-10 col-sm-offset-1">
												<div class="form-group">
													<label>Volunteers <b class="text-danger">*</b></label>
													<input name="volunteers" type="text" class="form-control" placeholder="John Doe">
												</div>
											</div>
										</div>
									</div>
								</div>
								<div class="wizard-footer height-wizard">
									<div class="pull-right">
										<input type='button' class='btn btn-next btn-fill btn-warning btn-wd btn-sm' name='next' value='Next' />
										<input type='submit' class='btn btn-finish btn-fill btn-warning btn-wd btn-sm' name='finish' value='Finish' />

									</div>

									<div class="pull-left">
										<input type='button' class='btn btn-previous btn-fill btn-default btn-wd btn-sm' name='previous' value='Previous' />
									</div>
									<div class="clearfix"></div>
								</div>

						</form>
					</div>
				</div>
			</div>
		</div>
	</div>

	<!--JS Files -->
	<script src="{{url_for('main.static',filename='js/jquery-2.2.4.min.js')}}" type="text/javascript"></script>
	<script src="{{url_for('main.static',filename='js/bootstrap.min.js')}}" type="text/javascript"></script>
	<script src="{{url_for('main.static',filename='js/jquery.bootstrap.wizard.js')}}" type="text/javascript"></script>
	<script src="{{url_for('main.static',filename='js/gsdk-bootstrap-wizard.js')}}"></script>
	<script src="{{url_for('main.static',filename='js/jquery.validate.min.js')}}"></script>
</body>

</html>

app/main/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" integrity="sha256-h20CPZ0QyXlBuAw7A+KluUYx/3pK+c7lYEpqLTlxjYQ=" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css">
    <link rel="stylesheet" href="{{url_for('main.static',filename='css/animate.css'}}">
    <link rel="stylesheet" href="{{url_for('main.static',filename='css/main.css'}}">
    <title>Landing Page</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand font-weight-bold logo donate-text-one" href="#">NGO SITE BUILDER</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav ml-lg-5">
                <li class="nav-item active">
                  <a class="nav-link font-weight-bold" href="{{url_for('main.index')}}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link font-weight-bold mx-lg-5" href="{{url_for('main.login')}}">Login</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link font-weight-bold" href="{{url_for('main.signup')}}">Sign Up</a>
                </li>
              </ul>
            </div>
          </nav>
    </header>


    <main class="container py-5">
        <div class="row">
        <div class="welc-section col-12 col-md-6">
            <h3><span class="welc">Welcome to</span> <br> <span class="ngo text-uppercase font-weight-bold">NGO SITE BUILDER</span></h3>
            <p class="welcome-text font-weight-light">This platform promises to serve as an avenue for non-governmental organizations to view
            all listed and available types of templates.</p>
            <a href="{{url_for('main.signup')}}" class="text-decoration-none"><button class="btn btn-welc-section border-text-one rounded p-2 text-white donate-bg-one my-2 my-sm-0" type="submit">Get Started</button></a>
        </div>
        <div class="col-12 col-md-6 mt-5 mt-lg-0">
            <img src="{{url_for('main.static',filename='img/ngo-welc-img.png')}}" class="image w-100" alt="NGO">
        </div>
        </div>
    </main>


  <footer class="container mt-5 text-center">
        <div class="footer-nav">
            <p class="py-2">This platform was built by <b class="donate-text-one">TEAM OHW-13</b></p>
        </div>
  </footer>



  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.slim.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.7/js/tether.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</body>
</html>

app/main/templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, user-scalable=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" integrity="sha256-h20CPZ0QyXlBuAw7A+KluUYx/3pK+c7lYEpqLTlxjYQ=" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{{url_for('main.static',filename='login.css')}}">
  <title>NGO Site Builder | Login Page</title>
</head>

<body>
  <div class="mainbody">

    <div class="container">
      <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
          <div class="card card-signin my-5">
            <div class="card-body">
              <h5 class="card-title text-center">Log In</h5>
              <form class="form-signin" name="loginForm" id="loginForm" method="POST">
                <div class="form-label-group">
                  <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus name="email">
                  <label for="inputEmail">Email address</label>
                </div>

                <div class="form-label-group">
                  <input type="password" id="inputPassword" class="form-control" placeholder="Password" required name="password">
                  <label for="inputPassword">Password</label>
                </div>

                <!-- <div class="custom-control custom-checkbox mb-3">
                                    <input type="checkbox" class="custom-control-input" id="customCheck1">
                                    <label class="custom-control-label" for="customCheck1">Remember password</label>
                                    <a href="#" class="fgtpass">Forgot Password</a>
                                </div> -->
                <button class="btn btn-lg btn-loginbbtn btn-block text-uppercase" id="submitloginAcc" type="submit">Log in</button>

              </form>
              <p class="text-center">Don't have an Account yet?<a href="{{url_for('main.signup')}}"> Sign Up</a></p>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>

</body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.slim.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>


</html>

app/main/templates/signup.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, user-scalable=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" integrity="sha256-h20CPZ0QyXlBuAw7A+KluUYx/3pK+c7lYEpqLTlxjYQ=" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{{url_for('main.static',filename='login.css')}}">
  <title>NGO Site Builder | Login Page</title>
</head>

<body>
  <div class="mainbody">

    <div class="container">
      <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
          <div class="card card-signin my-5">
            <div class="card-body">
              <h5 class="card-title text-center">Sign Up</h5>
              <p>Note: All fields are required</p>
              <form class="form-signin" name="loginForm" id="loginForm" method="POST">
                <div class="form-label-group">
                  <input type="text" id="inputEmail" class="form-control" placeholder="First Name" required autofocus name="firstName">
                  <label for="inputEmail">First Name</label>
                </div>

                <div class="form-label-group">
                  <input type="text" id="inputEmail" class="form-control" placeholder="Last Name" required autofocus name="lastName">
                  <label for="inputEmail">Last Name</label>
                </div>

                <div class="form-label-group">
                  <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus name="email">
                  <label for="inputEmail">Email address</label>
                </div>

                <div class="form-label-group">
                  <input type="password" id="inputPassword" class="form-control" placeholder="Password" required name="password">
                  <label for="inputPassword">Password</label>
                </div>

                <button class="btn btn-lg btn-loginbbtn btn-block text-uppercase" id="submitloginAcc" type="submit">SIGN UP</button>

              </form>
              <p class="text-center">Already have an Account?<a href="{{url_for('main.login')}}"> Log In</a></p>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>


</body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.slim.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>


</html>